### ISSUE TITLE
check and update arche-constants

### ISSUE THREAD

**Issue by csae8092** [arthur-schnitzler/schnitzler-briefe-static#112]
bitte schau mal die arche_constants.ttl (achtung ist jetzt ein .ttl file, sollte aber kein problem für dich sein) durch und aktualisiere sie
https://github.com/arthur-schnitzler/schnitzler-briefe-static/blob/2cbaf1c63852f3c4db22a29e62a9121fad8a3265/arche/arche_constants.ttl#L8

bei hasDescription vielleicht akutelle Zahlen zu Korrespondenzen und Briefen

aja, und ich würd auch die PDFs archivieren wenn das ok ist, vielleicht könntest du da auch noch die hasDescription und hasTitle (von collection editions) kontrollieren/ergänzen

wenn du die pdfs nicht in der ARCHE haben willst, dann schmeiß ich sie wieder raus

aja, so wird die neue arche aussehen https://arche-curation.acdh-dev.oeaw.ac.at/browser/metadata/140074

**Comment by martinantonmueller** [comment]
Erledigt – glaube ich.

**Comment by martinantonmueller** [comment]
Die neue ist ganz schön chic!
