### ISSUE TITLE
Goldmann facsimiles upload incomplete 

### ISSUE THREAD

**Issue by martinantonmueller** [arthur-schnitzler/schnitzler-briefe-static#33]
No clue why, but look here:
https://arthur-schnitzler.github.io/schnitzler-briefe-static/L02919.html
in the upload folder on the external harddisk there is but one file with the name starting with HS.NZ85.1.3170_ but it should be many

**Comment by laurauntner** [comment]
Goldmann-Bilder funktionieren allgemein nicht. Sehe ich mir an, wenn ich wieder im Büro bin.

**Comment by laurauntner** [comment]
Nachträge auf Festplatte gespielt, jetzt müssen sie noch in JP2 umgewandelt und auf den Server gespielt werden (Ordner mit neuen Bildern in Ordnungsliste gelb markiert).
