### ISSUE TITLE
formatierung blätter-url

### ISSUE THREAD

**Issue by martinantonmueller** [arthur-schnitzler/schnitzler-briefe-static#62]
diese sind falsch, fragezeichen am ende, doppelter schrägstrich in between
https://schnitzler-briefe.acdh.oeaw.ac.at//L02417.html?

**Comment by martinantonmueller** [comment]
das scheint mir an js/prev-next-urlupdate.js zu liegen, @linxOD kannst Du Dir das anschauen? wenn keine einstellungen vorgenommen sind, sollte er auch kein fragezeichen anhängen. bzw. der eine schrägstrich zu viel, danke!

**Comment by linxOD** [comment]
partial fix with 4f3cd06cfa41d031f0edfa37064cdbf4351fb30a
"?" will be fixed with next de-micro-editor release

**Comment by martinantonmueller** [comment]
Thank you!
