### ISSUE TITLE
typesense: new facets for correspondence

### ISSUE THREAD

**Issue by martinantonmueller** [arthur-schnitzler/schnitzler-briefe-static#75]
Es wäre schön, wenn man die Suchergebnisse nach einzelnen Korrespondenzen filtern könnte, also facets für die Korrespondenzen. Diese sind so vermerkt:

`<correspContext>
               <ref type="belongsToCorrespondence" target="correspondence_11485">Goldmann,
                  Paul</ref>`
                  
wobei es mehrere refs geben kann, beispielsweise wenn Hofmannsthal und Beer-Hofmann gemeinsam an Schnitzler eine Postkarte schreiben. Der xPath lautet:
`/tei:TEI/tei:teiHeader[1]/tei:profileDesc[1]/tei:correspDesc[1]/tei:correspContext[1]/tei:ref[@type='belongsToCorrespondence']`

**Comment by csae8092** [comment]
Oh, das sollte ich vielleicht einmal angehen ...

**Comment by csae8092** [comment]
not needed due to sender/receiver facets
