### ISSUE TITLE
problem with mentions

### ISSUE THREAD

**Issue by martinantonmueller** [arthur-schnitzler/schnitzler-briefe-static#88]
I've changed most references to "Sternwartestraße" to a more distinct "Sternwartestraße 71". 

This works in the letters:
https://schnitzler-briefe.acdh.oeaw.ac.at/L02603.html
and links here:
https://schnitzler-briefe.acdh.oeaw.ac.at/pmb168815.html
nevertheless there is no listing of the mentioned letters where "Sternwartestraße 71" is mentioned. 

It can’t be listPlace, as the website is properly created. What is it then?

**Comment by csae8092** [comment]
in the xml
```xml
<place xml:id="pmb168815">
<placeName>Sternwartestraße 71</placeName>
<desc type="entity_type">Wohngebäude (K.WHS)</desc>
<desc type="entity_type_id">36</desc>
<location type="coords">
<geo>48,23188 16,33716</geo>
</location>
<location type="located_in_place">
<placeName key="place__68">XVIII., Währing</placeName>
<geo>48,23333 16,31667</geo>
</location>
<location type="located_in_place">
<placeName key="place__150">Sternwartestraße</placeName>
<geo>48,23099349198 16,340117830625</geo>
</location>
<idno type="URL" subtype="pmb">https://pmb.acdh.oeaw.ac.at/entity/168815/</idno>
<listBibl>
<bibl type="collections" n="24">manually created entity</bibl>
</listBibl>
</place>
``` 

there is no 
`<note target="L03163.xml" corresp="1895-08-15" type="mentions">Felix Salten an Arthur Schnitzler, 15. 8. 1895</note>
`

**Comment by martinantonmueller** [comment]
Ah, thank you! Stupid me!
